### ISSUE TITLE
Todo calculation rasters

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-tools#111]
ToDo:
- [x] BaseCalculatorGPKG -> GridToRaster
- [ ] BaseCalculatorGPKG.from_folder kan weg
- [ ]  in nieuwe  branch in HRT:
   - [ ] hrt.DamageRaster(Raster) -> hrt.reproject_raster
   - [ ] hrt.gdf_to_raster (hrt.raster_functions.py)
   - [ ] hrt.sum_rasters([rasters]) hrt.raster_functions.py
- [ ] BaseCalculatorGPKG (GridToRaster) nalopen in alle py-bestanden
- [ ] folder deprecated weggooien
- [ ] #99

_Originally posted by @DanielTollenaar in https://github.com/threedi/hhnk-threedi-tools/issues/85#issuecomment-2012391120_
